services:
  llm:
    build: ./llm-engine
    container_name: "llm"
    networks:
      - default-net
    volumes:
      - './llm-engine/data:/data'
  
  backend:
    build: ./backend
    container_name: "backend"
    networks:
      - default-net
    volumes:
      - './backend/data:/data'
    ports:
      - 8000:8000

networks:
  default-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.190.128.0/24
