services:
  llm:
    build: ./llm-engine
    container_name: "llm"
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - default-net
    volumes:
      - './llm-engine/data:/data'
    ports:
      - 11434:11434
  
  backend:
    build: ./backend
    container_name: "backend"
    networks:
      - default-net
    volumes:
      - './backend/data:/chdb_data'
      - './backend/src:/app/api'
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    container_name: "frontend"
    networks:
      - default-net
    volumes:
      - './frontend/src:/front/'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mongo:
    build: ./database
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
    networks:
      - default-net

networks:
  default-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.190.128.0/24
